Fixes for installing in Python 3 (#410)
* setup.py: Python 3 doesn't support octal numbers in this syntax

* setup.py: ensure we can actually use the install_requires

* setup.py: ensure self.www_dir exists before we write to it

* setup.py: replace 'stdout.write' with 'print()'

Attempting to work around this error thrown on line 152:

    ValueError: underlying buffer has been detached

* setup.py: create the necessary directories in Python 3